#for transactions data set
#Job Submission Service
services:
  # Spark Master Service
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./app:/app
      - ./data_skew:/data

  # First Spark Worker Service
  spark-worker-1:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    volumes:
      - ./app:/app
      - ./data_skew:/data

  # Second Spark Worker Service
  spark-worker-2:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    volumes:
      - ./app:/app
      - ./data_skew:/data

  # Job Submission Service
  spark-job:
    image: bitnami/spark:latest
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    volumes:
      - ./app:/app
      - ./data_skew:/data
    command:
      - /opt/bitnami/spark/bin/spark-submit
      - --master
      - spark://spark-master:7077
      - /app/app.py